name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: ocaml/setup-ocaml@v1.1.11
    
    - name: Install ocaml
      run:  sudo apt install ocaml
    - name: Install ocamlbuild
      run:  sudo apt install ocamlbuild  
    - name: List all installed things
      run: ls /usr/bin/ocaml*
    - name: Compile
      run: make
      
    - name: Run tests
      run: make tests
    
